from __future__ import annotations

from dataclasses import asdict, is_dataclass
from typing import Any, Dict


def render_latex_results_fragment(result: Any) -> str:
    data = asdict(result) if is_dataclass(result) else result
    if not isinstance(data, dict):
        raise TypeError("result must be a dataclass or dict")
    if "runs" in data and "summary" in data:
        return _render_sweep_fragment(data)
    return _render_single_fragment(data)


def _render_single_fragment(data: Dict[str, Any]) -> str:
    control = data.get("control", {})
    sleep = data.get("sleep", {})
    by_domain = data.get("by_domain", {})
    lines = []
    lines.append("% Auto-generated by agentic_sleep.paper_tables")
    lines.append("\\paragraph{Auto-Generated Result Snapshot.}")
    lines.append("")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Auto-generated experiment snapshot.}")
    lines.append("\\begin{tabular}{lrr}")
    lines.append("\\toprule")
    lines.append("Metric & Control & Sleep \\\\")
    lines.append("\\midrule")
    for label, key in [
        ("Win Rate", "win_rate"),
        ("Deductive Accuracy", "deductive_accuracy"),
        ("Avg Entropy", "avg_entropy"),
        ("Token Budget", "token_budget"),
        ("Sleep Cycles", "sleep_cycles"),
        ("Consolidations", "consolidations"),
    ]:
        lines.append(f"{label} & {_fmt(control.get(key))} & {_fmt(sleep.get(key))} \\\\")
    if "heuristic_compression_ratio" in data:
        lines.append(
            f"HCR (global) & --- & {_fmt(data.get('heuristic_compression_ratio'))} \\\\"
        )
    if "consolidation_efficiency" in data:
        lines.append(
            f"$E_c$ & --- & {_fmt(data.get('consolidation_efficiency'))} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    if by_domain:
        lines.append("\\begin{table}[t]")
        lines.append("\\centering")
        lines.append("\\caption{Auto-generated domain breakdown.}")
        lines.append("\\begin{tabular}{lrrrr}")
        lines.append("\\toprule")
        lines.append("Domain & Ctrl WR & Sleep WR & Ctrl Acc & Sleep Acc \\\\")
        lines.append("\\midrule")
        for domain in sorted(by_domain.keys()):
            c = by_domain[domain].get("control", {})
            s = by_domain[domain].get("sleep", {})
            lines.append(
                f"{_escape(domain)} & {_fmt(c.get('win_rate'))} & {_fmt(s.get('win_rate'))} "
                f"& {_fmt(c.get('deductive_accuracy'))} & {_fmt(s.get('deductive_accuracy'))} \\\\"
            )
        lines.append("\\bottomrule")
        lines.append("\\end{tabular}")
        lines.append("\\end{table}")
        lines.append("")

    return "\n".join(lines)


def _render_sweep_fragment(data: Dict[str, Any]) -> str:
    summary = data.get("summary", {})
    paired = data.get("paired_deltas", {})
    by_domain = data.get("by_domain_summary", {})
    metadata = data.get("metadata", {})

    lines = []
    lines.append("% Auto-generated by agentic_sleep.paper_tables")
    lines.append("\\paragraph{Auto-Generated Seed Sweep Summary.}")
    lines.append("")
    lines.append(
        f"\\noindent Seeds: {_escape(str(metadata.get('seeds', [])))}; "
        f"games/domain={_escape(str(metadata.get('games_per_domain', 'NA')))}; "
        f"turns/game={_escape(str(metadata.get('turns_per_game', 'NA')))}."
    )
    lines.append("")

    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Seed-sweep aggregate metrics (mean $\\pm$ 95\\% CI).}")
    lines.append("\\begin{tabular}{lrr}")
    lines.append("\\toprule")
    lines.append("Metric & Control & Sleep \\\\")
    lines.append("\\midrule")
    for key, label in [
        ("win_rate", "Win Rate"),
        ("deductive_accuracy", "Deductive Accuracy"),
        ("avg_entropy", "Avg Entropy"),
        ("token_budget", "Token Budget"),
        ("sleep_cycles", "Sleep Cycles"),
        ("consolidations", "Consolidations"),
    ]:
        lines.append(
            f"{label} & {_dist(summary.get('control', {}).get(key))} & {_dist(summary.get('sleep', {}).get(key))} \\\\"
        )
    lines.append(
        f"Avg HCR & --- & {_dist(summary.get('sleep', {}).get('avg_hcr'))} \\\\"
    )
    lines.append(
        f"Global HCR & --- & {_dist(summary.get('global', {}).get('heuristic_compression_ratio'))} \\\\"
    )
    lines.append(
        f"$E_c$ & --- & {_dist(summary.get('global', {}).get('consolidation_efficiency'))} \\\\"
    )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Paired deltas across seeds (sleep minus control where applicable).}")
    lines.append("\\begin{tabular}{lr}")
    lines.append("\\toprule")
    lines.append("Metric & Mean $\\pm$ 95\\% CI \\\\")
    lines.append("\\midrule")
    for key, label in [
        ("delta_win_rate", "$\\Delta$ Win Rate"),
        ("delta_deductive_accuracy", "$\\Delta$ Deductive Accuracy"),
        ("token_budget_ratio_sleep_over_control", "Token Ratio (Sleep/Control)"),
    ]:
        lines.append(f"{label} & {_dist(paired.get(key))} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    if by_domain:
        lines.append("\\begin{table}[t]")
        lines.append("\\centering")
        lines.append("\\caption{Domain-level seed-sweep summary (mean metrics).}")
        lines.append("\\begin{tabular}{lrrrr}")
        lines.append("\\toprule")
        lines.append("Domain & Ctrl WR & Sleep WR & Ctrl Acc & Sleep Acc \\\\")
        lines.append("\\midrule")
        for domain in sorted(by_domain.keys()):
            c = by_domain[domain].get("control", {})
            s = by_domain[domain].get("sleep", {})
            lines.append(
                f"{_escape(domain)} & {_dist(c.get('win_rate'))} & {_dist(s.get('win_rate'))} "
                f"& {_dist(c.get('deductive_accuracy'))} & {_dist(s.get('deductive_accuracy'))} \\\\"
            )
        lines.append("\\bottomrule")
        lines.append("\\end{tabular}")
        lines.append("\\end{table}")
        lines.append("")

    return "\n".join(lines)


def _fmt(v: Any) -> str:
    if v is None:
        return "---"
    try:
        x = float(v)
    except (TypeError, ValueError):
        return _escape(str(v))
    if abs(x) >= 1_000_000:
        return f"{x:,.0f}"
    if abs(x) >= 1000:
        return f"{x:,.1f}"
    if abs(x) >= 1:
        return f"{x:.3f}".rstrip("0").rstrip(".")
    return f"{x:.4f}".rstrip("0").rstrip(".")


def _dist(d: Any) -> str:
    if not isinstance(d, dict):
        return "---"
    m = d.get("mean")
    lo = d.get("ci95_low")
    hi = d.get("ci95_high")
    if m is None or lo is None or hi is None:
        return "---"
    return f"{_fmt(m)} ({_fmt(lo)}, {_fmt(hi)})"


def _escape(s: str) -> str:
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("%", "\\%")
        .replace("&", "\\&")
        .replace("#", "\\#")
    )
